version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  - ./sessions:/usr/src/app/.wwebjs_auth
